server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: sa

  jpa:
    open-in-view: false
    database-platform: H2
    show-sql: true
    hibernate:
        ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info

api-server:
  kakao-api-server-url: https://dapi.kakao.com
  naver-api-server-url: https://openapi.naver.com

secrets:
  kakao-rest-api-key: KakaoAK b59375d0e881ccac07d04996b2496fd3
  x-naver-client-id-key: rNyjEScrdlU5n8Y_QnBR
  x-naver-client-secret-key: QblzCaOKNz
